### ISSUE TITLE
LDMatrix 'Input variant list does not contain any valid RS numbers or coordinates'

### ISSUE THREAD

**Issue by alicexrz** [CBIIT/LDlinkR#33]
Hello, I ran LDMatrix and the first chunk of code worked but not the second and third. The error message was "Error in LDmatrix(snps = c("chr6:2948731", "chr6:2948733"), pop = "EUR",  : error: Input variant list does not contain any valid RS numbers or coordinates.". I followed the required format "chr:pos" so not sure why they are invalid. 

LDmatrix(snps = c("chr13:32444611", "chr13:32509120"),
         pop = "EUR", r2d = "r2",
         token = "TOKEN")

LDmatrix(snps = c("chr6:2948731", "chr6:2948733"),
         pop = "EUR", r2d = "r2",
         token = "TOKEN")

LDmatrix(snps = c("chr8:75406699", "chr8:75406931"),
         pop = "EUR", r2d = "r2",
         token = "TOKEN")

**Comment by timyers** [comment]
Hello, thank you for your interest in `LDlinkR`.  Are you still experiencing an issue?
Thank you for providing reproducible examples.  I experienced the same error message using your code with the `LDlinkR::LDmatrix` function, which defaults to genome build GRCh37/hg19.  As far as I can determine, that build does not show reference SNPs at genomic coordinates chr6:2948731, chr6:2948733, chr8:75406699, and chr8:75406931.  This can be due to several factors and is likely the cause of the error you're seeing.  Please let me know if you believe this to be incorrect, and I'll investigate further.

**Comment by alicexrz** [comment]
I see. Thank you for taking the time to investigate!
